### ISSUE TITLE
report checklist

### ISSUE THREAD

**Issue by philsf** [philsf-biostat/SAR-2022-008-GJ#6]
- [ ] Title
- [ ] Date
- [ ] Objective
- [ ] Context (from SAP)
- [ ] Data & Methods (from SAP)
- [ ] Conclusions match the results
- [ ] Observations
- [ ] remove watermark
- [ ] update TOC
- [ ] render pdf
